# Generated by Django 5.1.7 on 2025-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.FloatField()),
                ('test_scores', models.FloatField()),
                ('assignments', models.FloatField()),
                ('performance_prediction', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
