# Generated by Django 5.1.7 on 2025-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no']},
        ),
        migrations.AddField(
            model_name='student',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='participation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='TEMP000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='test_scores',
            field=models.FloatField(default=0.0),
        ),
    ]
