# Generated by Django 5.1.7 on 2025-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField(default=1)),
                ('participation', models.FloatField(default=0.0)),
                ('assignments', models.FloatField(default=0.0)),
                ('test_scores', models.FloatField(default=0.0)),
                ('attendance', models.FloatField(default=0.0)),
                ('final_grade', models.FloatField(default=0.0)),
                ('performance_prediction', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
