services:
  - type: web
    name: student-performance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn student_performance.wsgi
    pythonVersion: 3.11.0
    autoDeploy: true
